services:
  - type: worker
    name: russia-monitor-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        value: {{ TELEGRAM_BOT_TOKEN }}
      - key: CHANNEL_ID1
        value: {{ CHANNEL_ID1 }}
      - key: CHANNEL_ID2
        value: {{ CHANNEL_ID2 }}
      - key: SUPABASE_URL
        value: {{ SUPABASE_URL }}
      - key: SUPABASE_KEY
        value: {{ SUPABASE_KEY }}
    region: frankfurt
    plan: free
