services:
  - type: worker
    name: news-bot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python worker.py"
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: CHANNEL_ID1
        sync: false
      - key: CHANNEL_ID2
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
